name: flutter_line_sdk
description: A Flutter plugin for using the LINE SDKs with Dart in Flutter apps.
version: 2.5.1
homepage: https://developers.line.biz/
repository: https://github.com/line/flutter_line_sdk/

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.linecorp.flutter_line_sdk
        pluginClass: FlutterLineSdkPlugin
      ios:
        pluginClass: FlutterLineSdkPlugin
